---
- name: Deploy Node.js application
  hosts: all
  vars:
    app_user: "nodeapp"
    app_name: "hello-world-app"
    service_path: "/opt/{{ app_name }}"
    node_version: "18.x"

  roles:
    - app
  tags: [app]
