{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pingserver.fullname" . }}
  labels:
    {{- include "pingserver.labels" . | nindent 4 }}
    release: prometheus
spec:
  jobLabel: app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
  selector:
    matchLabels:
      {{- include "pingserver.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
